  SERVICE:
    image: python:${SERVICE_NAME_PY_TAG:-3.10-slim}
    container_name: SERVICE
    restart: always
    command: >
      sh -c "${SERVICE_NAME_PY_REQUIREMENTS:+pip install -r requirements.txt &&} ${SERVICE_NAME_PY_CUSTOM_CMD:-python ${SERVICE_NAME_PY_STARTUP_FILE:-app.py}}"
    working_dir: ${SERVICE_NAME_PY_WORKDIR:-/var/www/html/}
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          cpus: "${SERVICE_NAME_PY_CPU:-0.1}"
          memory: "${SERVICE_NAME_PY_RAM:-0.1G}"
          pids: 100
    volumes:
      - html_data:/var/www/html/
    networks:
      - www
